# Build stage
FROM golang:1.17-alpine AS builder

# Install necessary build tools
RUN apk add --no-cache git build-base

WORKDIR /src/

# Copy source code
COPY . .

# Make sure the dist directory exists
RUN mkdir -p dist

# Build the Go application
RUN go build -tags webui -o /app/webapi ./cmd/webapi/

# Final stage
FROM alpine:latest

WORKDIR /app/

COPY --from=builder /app/webapi ./

EXPOSE 3000

CMD ["/app/webapi"]