FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare yarn@4.5.0 --activate

COPY webui/package.json webui/yarn.lock ./

RUN yarn install

COPY webui/ ./

RUN yarn run build-prod

FROM nginx:stable

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80