FROM golang:1.23.4 AS go_build
WORKDIR /build
COPY . .
RUN go build ./cmd/webapi

FROM ubuntu:latest
WORKDIR /backend
COPY --from=go_build /build/webapi .

VOLUME /backend/data
EXPOSE 3000
CMD ["./webapi"]